# NumPy

In [1]:
a=[2,3]

In [2]:
a*2

In [3]:
#NumPy=> Numerical Python
#open source library written mostly in C, C++ and partially in Python

In [4]:
import numpy

In [5]:
import numpy as np #alias

In [6]:
a_n=np.array(a)

In [7]:
marks=[23,34,56,78,67,89,65,45,45,99]

print(np.amin(marks)) #min
print(np.amax(marks)) #max
print(np.mean(marks)) #mean
print(np.median(marks)) #median
print(np.ptp(marks)) # point to point difference(max-min)
print(np.std(marks)) # standard deviation
print(np.var(marks)) #variance
print(np.average(marks)) #weightage is defined (wieghted average)

23
99
60.1
60.5
76
22.958440713602478
527.0899999999999
60.1


In [8]:
x=[34,45,67,78]
x_n=np.array(x)
np.std(x_n)

17.392527130926087

In [9]:
ss=np.mean((x_n-np.mean(x_n))**2)

In [10]:
ss

302.5

In [11]:
np.sqrt(ss)

17.392527130926087

# Random Numbers

In [12]:
from numpy import random

In [13]:
random.rand()

0.963644293793922

In [14]:
random.seed(12)
for i in range(10):
    print(random.rand())

0.15416284237967237
0.7400496965154048
0.26331501518513467
0.5337393933802977
0.014574962485419674
0.918747008099885
0.9007148541170122
0.03342142762634459
0.9569493362751168
0.13720932135607644


In [15]:
x=2.75 #seed
for i in range(10):
    x=1+(1-3.5)*x
    print(x)

-5.875
15.6875
-38.21875
96.546875
-240.3671875
601.91796875
-1503.794921875
3760.4873046875
-9400.21826171875
23501.545654296875


# NumPy Arrays

In [19]:
a=[[3,4], [5,6]]

In [20]:
a

[[3, 4], [5, 6]]

In [24]:
a[1][1]

6

In [28]:
import numpy as np
a_n=np.array(a)

In [29]:
a_n

array([[3, 4],
       [5, 6]])

In [30]:
a_n[0,:] #fetch a specific row (: => include all)

array([3, 4])

In [31]:
a_n[1,:]

array([5, 6])

In [32]:
a_n.dtype

dtype('int32')

In [36]:
#strides=> movement in memory to go to next: (row, cell)
a_n.strides

(8, 4)

In [38]:
#broadcasting of an array
a_n+1

array([[4, 5],
       [6, 7]])

In [39]:
a_n.shape

(2, 2)

In [41]:
b_n=np.array([1])
b_n

array([1])

In [42]:
b_n.shape

(1,)

In [44]:
a=np.loadtxt("https://raw.githubusercontent.com/goradbj/MachineLearning/main/cric.tsv",skiprows=1)
a

array([[  0., 100.,  78., 342.],
       [  1.,  11.,  62., 191.],
       [  2.,   8.,  85., 252.],
       [  3.,  71.,  24., 307.],
       [  4., 104.,  17., 229.],
       [  5.,  18., 104., 246.],
       [  6.,   8.,  76., 226.],
       [  7.,  86.,  74., 288.],
       [  8.,  12.,  60., 216.],
       [  9.,  25.,  90., 304.],
       [ 10.,  56.,   6., 272.],
       [ 11.,  88.,  69., 302.],
       [ 12., 147.,  65., 312.],
       [ 13., 121., 146., 370.],
       [ 15.,  99., 110., 362.]])

In [45]:
sachin_runs=a[:,1]
sachin_runs

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  25.,  56.,
        88., 147., 121.,  99.])

In [46]:
np.mean(sachin_runs)

63.6

In [47]:
dravid_runs=a[:,2]
np.mean(dravid_runs)

71.06666666666666

In [52]:
india_runs=a[:,3]
np.mean(india_runs)

281.26666666666665

In [53]:
np.corrcoef(sachin_runs,india_runs)  #corrcoef => coefficient of correlation

array([[1.        , 0.70460106],
       [0.70460106, 1.        ]])

In [54]:
np.corrcoef(dravid_runs,india_runs)

array([[1.        , 0.44853003],
       [0.44853003, 1.        ]])

In [55]:
np.corrcoef(sachin_runs,dravid_runs)

array([[1.        , 0.04899219],
       [0.04899219, 1.        ]])

#### shift+tab => jupyter documentation